<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table(table: 'course_modules')->insert([
            [
                'id'                        => 1,
                'course_category_id'        => 1,
                'name'                      => "Cyber Security for Beginners",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "cyber-security-for-beginners",
                'status'                    => 1,
                'short_description'         => "This module is designed to provide the user with the basic knowledge of how to avoid scams and identify fake emails and text messages.",
                'description'               => '<div class="ewa-rteLine">This module is designed to provide the user with the basic knowledge of how to avoid scams and identify fake emails and text messages. Our Cyber Security trainer will provide the latest up-to-date information on current and new scams. Our hands-on approach will leave you with the confidence and knowledge to know when something is not quite right on your phone, computer, or tablet.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 2,
                'course_category_id'        => 2,
                'name'                      => "Coding for Beginners",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "coding-for-beginners",
                'status'                    => 1,
                'short_description'         => 'Coding for beginners will provide the young ones with an understanding of how software is put together.',
                'description'               => '<div class="ewa-rteLine">Coding for beginners will provide the young ones with an understanding of how software is put together. Simple coding will provide the building blocks to start a future in coding.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 3,
                'course_category_id'        => 2,
                'name'                      => "Coding for Web Pages",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "coding-for-web-pages",
                'status'                    => 1,
                'short_description'         => 'Coding for web pages is an extension to Coding for Beginners.',
                'description'               => '<div class="ewa-rteLine">Coding for web pages is an extension to Coding for Beginners. In this module, we will learn all the fundamentals of designing your first web page. From start to finish.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 4,
                'course_category_id'        => 3,
                'name'                      => "Word Processing for Beginners",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "word-processing-for-beginners",
                'status'                    => 1,
                'short_description'         => 'Word Processing for beginners will utilize MS Word and Apple Pages to create documents. Save the document',
                'description'               => '<div class="ewa-rteLine">Word Processing for beginners will utilize MS Word and Apple Pages to create documents. Save the document. Edit the document and finally print the document in PDF and on the printer. We take the guesswork out and teach you all the basic functions so that you get a great result.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 5,
                'course_category_id'        => 3,
                'name'                      => "Spread Sheets for Beginners",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "spread-sheets-for-beginners",
                'status'                    => 1,
                'short_description'         => "Let's face it, spreadsheets are everywhere in business. Get a head start and learn the basics of MS Excell or Apple Numbers.",
                'description'               => '<div class="ewa-rteLine">Lets face it, spreadsheets are everywhere in business. Get a head start and learn the basics of MS Excell or Apple Numbers. We teach you what spreadsheets are all about and how to maximize your ability when it comes to calculating within the spreadsheet. We also show you how to print your spreadsheet in PDF and on your printer.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 6,
                'course_category_id'        => 3,
                'name'                      => "Presentations for Beginners",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "presentations-for-beginners",
                'status'                    => 1,
                'short_description'         => 'Presentations for beginners are the perfect way to launch yourself into PowerPoint presentations or Apple Keynotes.',
                'description'               => '<div class="ewa-rteLine">Presentations for beginners are the perfect way to launch yourself into PowerPoint presentations or Apple Keynotes. We provide insight into all the features and functions that will enable you to create your own presentations.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 7,
                'course_category_id'        => 3,
                'name'                      => "Movie Creation for Beginners",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "movie-creation-for-beginners",
                'status'                    => 1,
                'short_description'         => 'We are all taking photographs and videos these days. With these photographs and movies, we can design and create our own movies.',
                'description'               => '<div class="ewa-rteLine">We are all taking photographs and videos these days. With these photographs and movies, we can design and create our own movies. We will teach you the process from start to finish. You can be the producer of your own Movies. No matter whether you are producing movies for your family or for multimedia. This is a great start that will bring out your creative touch.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 8,
                'course_category_id'        => 1,
                'name'                      => "Cyber Security - The Technical Aspects",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "cyber-security-the-technical-aspects",
                'status'                    => 1,
                'short_description'         => 'This package will provide technical knowledge of the incoming threats and how to identify them.',
                'description'               => '<div class="ewa-rteLine">This  package will provide technical knowledge of the incoming threats and how to identify them. Both Social Engineering attacks and cyber-attacks are covered in addition to using online tools to identify bogus websites, phone numbers, and email addresses.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 9,
                'course_category_id'        => 1,
                'name'                      => "Cyber Security Updater",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "cyber-security-updater",
                'status'                    => 1,
                'short_description'         => 'In this module, we present the latest in threats and methods to reduce your risk while online.',
                'description'               => '<div class="ewa-rteLine">In this module, we present the latest in threats and methods to  reduce your risk while online. We utilize our Cyber Security team to provide the training in this package. You will be provided with all the latest in the world of cyber security.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 10,
                'course_category_id'        => 3,
                'name'                      => "MS Word & Mail Merge",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "ms-word-mail-merge",
                'status'                    => 1,
                'short_description'         => 'In this package, we specifically cover mail merge.',
                'description'               => '<div class="ewa-rteLine">In this package, we specifically cover mail merge. This is the function of providing a word with a predefined list of people you would like to send a pre-defined letter or email. This is great for sales or community groups where you can send a regular email to your list of members or customers. This is the way into sending your own EDM.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],

            [
                'id'                        => 11,
                'course_category_id'        => 4,
                'name'                      => "Setting up the Network",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "setting-up-the-network",
                'status'                    => 1,
                'short_description'         => 'The consistency of a healthy network is paramount. All too often network devices outgrow the capability of existing equipment.',
                'description'               => '<div class="ewa-rteLine">The consistency of a healthy network is paramount. All too often network devices outgrow the capability of existing equipment. In this module, we provide technicians with the knowledge and understanding to set up new networks and upgrade existing networks to cope with increased traffic, devices, and users.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 12,
                'course_category_id'        => 4,
                'name'                      => "Diagnosing a Windows Disk Faults",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "diagnosing-a-windows-disk-faults",
                'status'                    => 1,
                'short_description'         => 'One of the most common faults experienced with personal windows computers is main storage disk failure.',
                'description'               => '<div class="ewa-rteLine">One of the most common faults experienced with personal windows computers is main storage disk failure. We provide the processes and training to diagnose the fault correctly so that the appropriate action can be taken on behalf of the customer. When the main storage drive fails, there is a high probability that data will be lost. We provide a details plan to ensure the best possible outcome can be achieved.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 13,
                'course_category_id'        => 4,
                'name'                      => "Performing a Windows System Health Check",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "performing-a-windows-system-health-check",
                'status'                    => 1,
                'short_description'         => 'Health checks on computers are a function that is performed to ensure the computer does not have any critical faults looming.',
                'description'               => '<div class="ewa-rteLine">Health checks on computers are a function that is performed to ensure the computer does not have any critical faults looming. While our computers operate without a hitch for long periods of time, when the system literally breaks down, there is a high chance that there will be data loss if the main storage media is the cause of failure. Providing regular health checks to mission-critical computers is paramount and we will show you how.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 14,
                'course_category_id'        => 4,
                'name'                      => "Knowing the MAC and onboard tools",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "knowing-the-mac-and-onboard-tools",
                'status'                    => 1,
                'short_description'         => 'Most seasoned technicians have vast experience with the Windows operating system as windows were adopted by so many businesses and private users.',
                'description'               => '<div class="ewa-rteLine">Most seasoned technicians have vast experience with the Windows operating system as windows were adopted by so many businesses and private users.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 15,
                'course_category_id'        => 1,
                'name'                      => "Cyber Security for Technicians",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "cyber-security-for-technicians",
                'status'                    => 1,
                'short_description'         => 'Cyber Security for Technicians includes some aspects of Cyber Security for Beginners to provide a detailed insight into where the customer may have made an error in judgment.',
                'description'               => '<div class="ewa-rteLine">Cyber Security for Technicians includes some aspects of Cyber Security for Beginners to provide a detailed insight into where the customer may have made an error in judgment. We cover the latest scams and social engineering. Processes and procedures to recover data from an infected device. Also how to completely clean the device. Overview of Zero Day threats and the effectiveness of antivirus software. Overview of Wireshark and how to become an active threat hunter when high traffic is being experienced on a customers system.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
            [
                'id'                        => 16,
                'course_category_id'        => 1,
                'name'                      => "Cyber Security Technical Monthly Update",
                'code'                      => "",
                'rating'                    => "5",
                'slug'                      => "cyber-security-technical-monthly-update",
                'status'                    => 1,
                'short_description'         => 'Technical Monthly Update is a report of all the latest news and research on Cyber Security that is being experienced in the real world.',
                'description'               => '<div class="ewa-rteLine">Technical Monthly Update is a report of all the latest news and research on Cyber Security that is being experienced in the real world. With the constantly changing Cyber Security landscape, many of our customers are requesting a technical overview of the previous month.</div><p></p>',
                'created_at'                => now(),
                'updated_at'                => now(),
            ],
//            [
//                'id'                        => 17,
//                'course_category_id'        => 5,
//                'name'                      => "Transition from Windows to a Mac",
//                'code'                      => "",
//                'rating'                    => "5",
//                'slug'                      => "transition-from-windows-to-a-mac",
//                'status'                    => 1,
//                'short_description'         => 'If you have never used a mac previously, the change may seem overwhelming. Geeks Learning will make the transition to Mac a pleasurable experience.',
//                'description'               => '<div class="ewa-rteLine">If you have never used a mac previously, the change may seem overwhelming. Geeks Learning will make the transition to Mac a pleasurable experience. We show you where the equivalent functions are in Mac so that you will start to feel good about your new purchase. Macs are actually easier to use than Windows and provide seamless integration with iPad and iPhones. We can show you how.</div><p></p>',
//                'created_at'                => now(),
//                'updated_at'                => now(),
//            ],
//            [
//                'id'                        => 18,
//                'course_category_id'        => 5,
//                'name'                      => "Using Pages, Numbers and Keynotes",
//                'code'                      => "",
//                'rating'                    => "5",
//                'slug'                      => "using-pages-numbers-and-keynotes",
//                'status'                    => 1,
//                'short_description'         => 'Pages, Numbers, and Keynotes are equivalent to Word, Excell, and PowerPoint. While the applications look very different, their core function is the same.',
//                'description'               => '<div class="ewa-rteLine">Pages, Numbers, and Keynotes are equivalent to Word, Excell, and PowerPoint. While the applications look very different, their core function is the same. I know when I first used Pages, I thought how hard is this going to be? Well,  the experience is actually easier and I use Mac applications for most of my daily work. Let us get you started on the simplicity and added functionality of apple.</div><p></p>',
//                'created_at'                => now(),
//                'updated_at'                => now(),
//            ],
//            [
//                'id'                        => 19,
//                'course_category_id'        => 6,
//                'name'                      => "Setting up & Using your iPhone",
//                'code'                      => "",
//                'rating'                    => "5",
//                'slug'                      => "setting-up-using-your-iphone",
//                'status'                    => 1,
//                'short_description'         => 'The first time you use an iPhone, the experience is quite different from other android devices.',
//                'description'               => '<div class="ewa-rteLine">The first time you use an iPhone, the experience is quite different from other android devices. If you are still experiencing difficulties navigating around the iPhone and need some guidance to make your life easier, we can show you.</div><p></p>',
//                'created_at'                => now(),
//                'updated_at'                => now(),
//            ],
//            [
//                'id'                        => 20,
//                'course_category_id'        => 6,
//                'name'                      => "Setting up & Using your Android Phone",
//                'code'                      => "",
//                'rating'                    => "5",
//                'slug'                      => "setting-up-using-your-android-phone",
//                'status'                    => 1,
//                'short_description'         => 'The first time you use an android smartphone, the experience is quite different from other android devices.',
//                'description'               => '<div class="ewa-rteLine">The first time you use an android smartphone, the experience is quite different from other android devices. If you are still experiencing difficulties navigating around the phone and need some guidance to make your life easier, we can show you.</div><p></p>',
//                'created_at'                => now(),
//                'updated_at'                => now(),
//            ],
//            [
//                'id'                        => 21,
//                'course_category_id'        => 7,
//                'name'                      => "The Basics of Windows",
//                'code'                      => "",
//                'rating'                    => "5",
//                'slug'                      => "the-basics-of-windows",
//                'status'                    => 1,
//                'short_description'         => 'When we first start using a windows computer we only use the applications that are relevant to our needs.',
//                'description'               => '<div class="ewa-rteLine">When we first start using a windows computer we only use the applications that are relevant to our needs. Windows operating system and available applications can make our lives easier. Its just knowing how to use them that is the key. Geeks Learning will provide you with the skills and knowledge to impress your family.</div><p></p>',
//                'created_at'                => now(),
//                'updated_at'                => now(),
//            ],


        ]);
    }
}
